MarxMustermann/OfMiceAndMechs

help.md
=> added comand

.idea/.gitignore, executeMe.py, executeYou.py, src/characters.py
Please also include the.gitignore. They are essential to keep my code editor functioning properly without weird shenanigans.'
This is an example of proper PEP 8, excluding naming conventions.
=> show example of pep 8

executeMe.py, src/chats.py, src/items.py
=> Minor Changes

src/questFolder/beUsefull.py, src/questFolder/buildRoom.py, src/questFolder/goToTerrain.py, src/questFolder/machinePlacing.py, src/questFolder/scheduleMetalWorking.py
Fixed Some Code Based On Linter Suggestions
=> Cleaned Code

src/questFolder/ascend.py, src/questFolder/assignFloorPlan.py, src/questFolder/clearTile.py, src/questFolder/getPromotion.py, src/quests.py
- Added MetaQuestSequenceV2 Interface
- Cleaned Quests: Ascend and Clear_Tile
- Converted GetPromotion to New Interface
- Fixed Some Issues
OfMiceAndMechs :                              Total
Editor time :                             58 min
Active code time :                             10 min
Lines of code added :                                170
Lines of code deleted :                                493
Total keystrokes :                                531
-------------------------------------------------------------------
=> Added New Interface

src/questFolder/clearPathToPosition.py, src/questFolder/goHome.py
- Fixed ClearPath
- Moved GoHome to new interface
```             
OfMiceAndMechs :                              Total
Editor time :                            1.2 hrs
Active code time :                             12 min
Lines of code added :                                228
Lines of code deleted :                                590
Total keystrokes :                                603
```
=> Fixed Bugs

src/questFolder/goHome.py
OfMiceAndMechs :                              Total
Editor time :                            3.1 hrs
Active code time :                             30 min
Lines of code added :                              1,398
Lines of code deleted :                             12,602
Total keystrokes :                              1,148
=> Fixed GoHome

src/questFolder/beUsefull.py, src/questFolder/eat.py, src/questFolder/refillPersonalFlask.py
OfMiceAndMechs :                              Total
Editor time :                            5.6 hrs
Active code time :                            1.2 hrs
Lines of code added :                              5,880
Lines of code deleted :                             16,577
Total keystrokes :                              2,558
=> Moved Eat and Refill Flask fom BeUseful

.gitignore, src/questFolder/huntdown.py, src/questFolder/runCommand.py
added time counter to gitignore
=> Fixed Missing Conversation

src/questFolder/assignFloorPlan.py, src/questFolder/beUsefull.py, src/questFolder/buildRoom.py, src/questFolder/cleanSpace.py, src/questFolder/clearInventory.py, src/questFolder/drawFloorPlan.py, src/questFolder/eat.py, src/questFolder/fetchItems.py, src/questFolder/fillFlask.py, src/questFolder/gatherScrap.py, src/questFolder/gatherVatMaggots.py, src/questFolder/getEpochReward.py, src/questFolder/machinePlacing.py, src/questFolder/machining.py, src/questFolder/manufacture.py, src/questFolder/metalWorking.py, src/questFolder/operateMachine.py, src/questFolder/pray.py, src/questFolder/refillPersonalFlask.py, src/questFolder/restockRoom.py, src/questFolder/scavenge.py, src/questFolder/scrapHammering.py, src/quests.py
OfMiceAndMechs
Total Time: 3:20H
=> Converted BeUseful to MetaQuestV2

.gitignore, config/displayChars.py, executeMe.py, src/interaction.py, src/menuFolder/SettingMenu.py, src/menuFolder/__init__.py
Removed Tutorial difficulty Option
Total Time: 08:40H
=> Cleaned code and Added Settings For Sound

src/characters.py, src/itemFolder/health/__init__.py, src/itemFolder/health/regenerator.py, src/story.py
=> Added regenerator

src/itemFolder/health/regenerator.py, src/questFolder/__init__.py, src/questFolder/story/activateRegenerator.py, src/story.py
=> Added Regenerator Activation Quest

src/itemFolder/story/sternsContraption.py, src/questFolder/secureTile.py, src/quests.py, src/story.py
=> Added Wandering Behavior

src/rooms.py
=> Fixed Enemy Rendering Inside Rooms

src/CharcFolder/Spider.py, src/CharcFolder/Spiderling.py, src/menuFolder/SettingMenu.py, src/overlays.py
=> Added Color Cycling background and fixed a bug

src/interaction.py, src/menuFolder/SettingMenu.py
=> Added FullScreen Setting to the menu and fixed bugs

executeMe.py, src/interaction.py, src/menuFolder/SettingMenu.py, src/overlays.py
=> Added option for toggling synchronize_enemy_blinking + fixed Crash

src/CharcFolder/Statue.py, src/CharcFolder/Statuette.py, src/pseudoUrwid.py, src/story.py
=> Added Variance to Statue Color

src/StateFolder/__init__.py, src/StateFolder/death.py, src/__init__.py, src/story.py
=> Added Death Screen

src/StateFolder/death.py, src/characters.py, src/helpers.py, src/story.py
=> Added The killer to death screen and fixed bug

src/StateFolder/death.py, src/helpers.py, src/interaction.py, src/pseudoUrwid.py, src/story.py
=> Improved the Death Screen

src/characterFolder/clone.py, src/cinematicsFolder/death.py, src/helpers.py, src/itemFolder/functional/corpseAnimator.py, src/itemFolder/functional/growthTank.py, src/itemFolder/resources/__init__.py, src/itemFolder/resources/implant.py, src/story.py
=> Added Implants

src/itemFolder/resources/implant.py, src/itemFolder/workshops/__init__.py, src/itemFolder/workshops/implantresearchcenter.py, src/menuFolder/debugMenu.py
=> Added Implant Research Center

src/interaction.py
4:24H
Improvements:
- Centered Main Menu
- Fixed Bug that prevented characters from advancing
=> Improvment to main menu

src/interaction.py
=> Fixed Intro Animation Positioning

src/itemFolder/workshops/memoryReader.py, src/story.py
=> added Fragments Stitching

src/interaction.py
=> Fixed Off center Intro Text

src/interaction.py
=> Fixed Run Intro

src/characters.py, src/magic.py, src/menuFolder/mapMenu.py, src/overlays.py, src/questFolder/assignFloorPlan.py, src/questFolder/beUsefull.py, src/questFolder/buildRoom.py, src/questFolder/designateRoom.py, src/questFolder/drawFloorPlan.py, src/questFolder/getPromotion.py, src/questFolder/machinePlacing.py, src/questFolder/machining.py, src/questFolder/metalWorking.py, src/questFolder/scheduleRoomBuilding.py, src/questFolder/scrapHammering.py, src/questFolder/setUpMachine.py, src/rooms.py, src/story.py
=> spawned npc and improved code to accommodate non centeral locations of bases

src/gamestate.py, src/interaction.py, src/itemFolder/logistics/__init__.py, src/itemFolder/logistics/dimensionTeleporter.py, src/menuFolder/__init__.py, src/menuFolder/confirmMenu.py, src/menuFolder/teleporterGroupMenu.py, src/menuFolder/warningMenu.py
=> Added DimensionTeleporter With Needed UI

src/interaction.py, src/itemFolder/logistics/dimensionTeleporter.py, src/menuFolder/__init__.py, src/menuFolder/directionMenu.py, src/menuFolder/teleporterGroupMenu.py
=> added operation direction to teleporters

src/itemFolder/logistics/dimensionTeleporter.py, src/menuFolder/directionMenu.py, src/menuFolder/teleporterGroupMenu.py, src/menuFolder/warningMenu.py
=> Improved UI for teleporter

src/itemFolder/functional/glassHeart.py, src/itemFolder/industry/machine.py, src/itemFolder/logistics/dimensionTeleporter.py, src/itemFolder/military/__init__.py, src/itemFolder/military/enemyCaller.py, src/itemFolder/resources/implant.py, src/itemFolder/story/implantManipulator.py, src/itemFolder/story/memoryFragment.py, src/itemFolder/workshops/__init__.py, src/itemFolder/workshops/implantresearchcenter.py, src/itemFolder/workshops/manufacturingTable.py, src/itemFolder/workshops/memoryReader.py, src/itemFolder/workshops/metalWorkingBench.py, src/itemFolder/workshops/teleporterManufacturer.py, src/itemFolder/workshops/workShop.py, src/items.py, src/menuFolder/debugMenu.py, src/story.py
=> Improved Lab and changed manufacturing behaviors

src/menuFolder/debugMenu.py, src/popupFolder/__init__.py, src/popupFolder/enterRuinTerrain.py, src/popupFolder/enterShrineTerrain.py, src/popupFolder/entreLabTerrain.py, src/terrains.py
=> Implemented Popups upon Entering new terrain

src/menuFolder/debugMenu.py
=> added clear fog option to debug menu

TODO.md, src/characters.py, src/interaction.py, src/menuFolder/TerrainMenu.py, src/menuFolder/__init__.py, src/menuFolder/debugMenu.py
=> made debug terrain teleport use terrain menu

TODO.md, src/gamestate.py, src/helpers.py, src/interaction.py, src/itemFolder/logistics/dimensionTeleporter.py, src/magic.py, src/menuFolder/teleporterGroupMenu.py, src/story.py
=> Major Imporvments to Teleporters

src/itemFolder/workshops/swordSharpener.py, src/popupFolder/enterRoom.py
=> fixed bug and made grindstone less op

TODO.md, src/characterFolder/golem.py, src/characterFolder/mechanicalCrawler.py, src/monster.py
=> fixed shades of red for dungeon enemies for all difficulty modes

TODO.md, src/itemFolder/functional/glassStatue.py, src/menuFolder/TerrainMenu.py, src/popups.py
=> Couple Improvments

src/characterFolder/golem.py, src/characterFolder/mechanicalCrawler.py, src/monster.py
=> changed multiplier amount of influence on movement speed

src/characters.py, src/itemFolder/workshops/alchemyTable.py, src/itemFolder/workshops/anvil.py, src/itemFolder/workshops/implantresearchcenter.py, src/itemFolder/workshops/machiningTable.py, src/itemFolder/workshops/manufacturingTable.py, src/itemFolder/workshops/memoryReader.py, src/itemFolder/workshops/metalWorkingBench.py, src/itemFolder/workshops/teleporterManufacturer.py, src/menuFolder/__init__.py, src/menuFolder/characterInfoMenu.py, src/menuFolder/characterStatsMenu.py, src/rooms.py, src/terrains.py
=> Added Stats Menu

src/itemFolder/workshops/armorReinforcer.py, src/itemFolder/workshops/swordSharpener.py, src/itemFolder/workshops/workShop.py, src/menuFolder/sliderMenu.py
=> Fixed SwordSharpener

src/itemFolder/workshops/armorReinforcer.py, src/itemFolder/workshops/swordSharpener.py, src/menuFolder/sliderMenu.py
Fixed ArmorReinforcer and SwordSharpener Upgrade Logic
Total Time:  3:58H
=> Improved SliderMenu

src/helpers.py, src/monster.py
=> added better random distribution

src/gamestate.py, src/helpers.py, src/interaction.py, src/monster.py, src/story.py
=> added Custom Difficulty

src/characterFolder/guardian.py, src/characterFolder/shieldbug.py, src/interaction.py, src/itemFolder/military/enemyCaller.py, src/monster.py, src/story.py
=> Added More Difficulty Options Sliders

.gitignore, data/difficultyMap.json, src/interaction.py, src/monster.py
=> added custom saved difficulties

src/characterFolder/snatcher.py, src/characterFolder/spider.py, src/characters.py, src/itemFolder/functional/throne.py, src/items.py, src/popupFolder/__init__.py, src/popupFolder/addedStatusEffect.py
=> added popups for status effect

src/menuFolder/questMenu.py, src/questFolder/clearInventory.py, src/questFolder/clearPathToPosition.py, src/questFolder/clearTerrain.py, src/questFolder/clearTile.py, src/questFolder/consumePotion.py, src/questFolder/deleteMarking.py, src/questFolder/discardItemsInside.py, src/questFolder/eat.py, src/questFolder/enterRoom.py, src/questFolder/equip.py, src/questFolder/farmMold.py, src/questFolder/fetchItems.py, src/questFolder/fight.py, src/questFolder/flee.py, src/questFolder/gatherScrap.py, src/questFolder/gatherVatMaggots.py, src/questFolder/goToPosition.py, src/questFolder/goToTerrain.py, src/questFolder/goToTile.py, src/questFolder/heal.py, src/questFolder/placeItem.py
=> added default high level quests highlighting in the quest menu

executeYou.py, src/canvas.py, src/interaction.py
=> added exhaustion bar on characters and bug fix

src/cinematicsFolder/death.py
=> Fixed Death Screen Calc

src/cinematicsFolder/death.py
=> improved Pre Death Screen and simplified it

src/chats.py, src/itemFolder/automation/command.py, src/itemFolder/functional/growthTank.py, src/itemFolder/story/integrator.py
=> added protections preventing assimilation accidentally

src/questFolder/goToTerrain.py, src/questFolder/story/adventure.py, src/questFolder/story/adventureOnTerrain.py
=> made the solver avoid the end dungeon when adventuring

src/questFolder/gatherScrap.py, src/questFolder/story/collectGlassHearts.py
=> CollectGlassHearts now wishes for ScrapField
